hspc_home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls

import website.urls

app_name = 'hspc_home'

urlpatterns = [
    url(r'^', include((website.urls.urlpatterns, 'hspc_home.website'), namespace='website')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
    url(r'', include(wagtail_urls)),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from website.views import EventListView, RegistrationRequestView, RegistrationRequestSuccessView, AnnouncementListView, \
    NewsListView

app_name = 'website'

urlpatterns = [
    url(r'^events/$', EventListView.as_view(), name="event-list"),
    url(r'^announcements/$', AnnouncementListView.as_view(), name='announcement-list'),
    url(r'^newsroom/$', NewsListView.as_view(), name='newsroom-list'),

    url(
        r'^membership/join/request/submitted/$',
        RegistrationRequestSuccessView.as_view(),
        name="registration-request-submitted"
    ),
    url(
        r'^membership/join/request/$',
        RegistrationRequestView.as_view(success_url="/membership/join/request/submitted/"),  # Can't use reverse() since the urlspatterns aren't built yet
        name="registration-request"
    ),
]

website/models.py
from datetime import datetime

from django.db import models
from django.contrib.flatpages.models import FlatPage
from wagtailmenus.models import MenuPage, MainMenuItem
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Page
from wagtail.core import blocks
from wagtail.admin.edit_handlers import FieldPanel, StreamFieldPanel
from wagtail.images.blocks import ImageChooserBlock

from website.blocks import HomepagePanelBlock


class EventCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "event categories"


class Event(models.Model):
    category = models.ForeignKey(EventCategory, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=128)
    hidden_date = models.DateTimeField(default=datetime.now, help_text='Used to sort events', verbose_name='sortable date')
    end_date = models.DateTimeField(default=datetime.now, help_text='After this date/time the event will move to the "Archived" section', verbose_name='expiration date')
    display_date = models.CharField(max_length=128, help_text="Text shown such as 'Feb 4th - 8th' or 'March 25'")
    location = models.CharField(max_length=128)
    event_details = RichTextField()

    def __str__(self):
        return self.title
    class Meta:
        ordering = ["hidden_date"]


class Announcement(models.Model):
    hidden_label = models.CharField(max_length=255, help_text='Only displayed in the CMS or Admin UI.')
    created = models.DateTimeField(default=datetime.now, editable=False)
    announcement = RichTextField()

    def __str__(self):
        return self.hidden_label


class NewsMention(models.Model):
    source = models.CharField(max_length=255)
    date = models.DateField()
    url = models.URLField()
    article_title = models.CharField(max_length=255)

    def __str__(self):
        return "{} - {}".format(self.source, self.date)


class RegistrationRequest(models.Model):
    full_name = models.CharField(max_length=255)
    title = models.CharField(max_length=255, blank=True, null=True)
    organization_name = models.CharField(max_length=255, blank=True, null=True)
    email_address = models.EmailField()
    phone_number = models.CharField(max_length=64)
    comments = models.TextField(blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        sane_full_name = self.full_name.strip()

        if self.title is None or self.title.strip() == "":
            return sane_full_name
        else:
            return "{} ({})".format(sane_full_name, self.title)



'''
# # # # # # # # # # # # # # # # # # # #
# # #  Begin Wagtail-based models # # #
# # # # # # # # # # # # # # # # # # # #
'''

class HomePage(MenuPage):

    body = StreamField([
        ('homepage_panel', HomepagePanelBlock()),
    ], blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]


class BasicInfoPage(MenuPage):
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
    ]


class RobustInfoPage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('separator', blocks.StaticBlock()),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]

'''
# # # # # # # # # # # # # # # # # # # #
# # #  End Wagtail-based models # # #
# # # # # # # # # # # # # # # # # # # #
'''

website/forms.py
from django.forms import ModelForm

from .models import RegistrationRequest


class RegistrationRequestForm(ModelForm):
    class Meta:
        model = RegistrationRequest
        fields = [
            "full_name",
            "title",
            "organization_name",
            "email_address",
            "phone_number",
            "comments"
        ]

website/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, View

from website.forms import RegistrationRequestForm
from website.models import EventCategory, Announcement, NewsMention


class EventListView(ListView):

    model = EventCategory
    template_name = "website/events.html"

    def get_context_data(self, **kwargs):
        return super(EventListView, self).get_context_data(**kwargs)


class AnnouncementListView(ListView):
    model = Announcement
    template_name = "website/announcements.html"
    queryset = Announcement.objects.order_by('-created')

    def get_context_data(self, **kwargs):
        return super(AnnouncementListView, self).get_context_data(**kwargs)


class NewsListView(ListView):
    model = NewsMention
    template_name = 'website/newsroom.html'


class RegistrationRequestView(CreateView):
    form_class = RegistrationRequestForm
    template_name = "website/registration/request.html"


class RegistrationRequestSuccessView(View):
    def get(self, request):
        return render(request, "website/registration/request_success.html")

templates/base.html
{% load static %}
{% load menu_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HSPC | {% block page_title %}{% endblock %}</title>
    <meta name="description" content="HSPC is a provider-led and vendor-involved consortium dedicated to establishing a scalable, truly interoperable data and services architecture for healthcare.">
    <meta name="author" content="HSPC Members">
    <meta name="robots" content="index,follow,noodp" />

    <link rel="apple-touch-icon" sizes="57x57" href="{% static "icons/apple-icon-57x57.png" %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static "icons/apple-icon-60x60.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "icons/apple-icon-72x72.png" %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "icons/apple-icon-76x76.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "icons/apple-icon-114x114.png" %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static "icons/apple-icon-120x120.png" %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static "icons/apple-icon-144x144.png" %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static "icons/apple-icon-152x152.png" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "icons/apple-icon-180x180.png" %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static "icons/android-icon-192x192.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "icons/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "icons/favicon-96x96.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "manifest.json" %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#4774a2">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static "vendor/cosmo.bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
    <link rel="stylesheet" href="{% static "styles/header.css" %}">
    <link rel="stylesheet" href="{% static "styles/footer.css" %}">
    {% block styles %}{% endblock %} {# Used so subpages can inject thier own styles #}

    <script src="https://use.typekit.net/fcm2zhl.js" defer></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>

</head>
<body class="{% block body_class %}{% endblock %}">

<div class="before-header">
    <div class="container">
        <div class="row">
            <header>
                <div class="header-reset">
                    <a class="logo-link" href="/">
                        <img alt="HSPC Logo" style="max-height: 48px" src="{% static "imgs/old-hspc-logo.png" %}">
                    </a>
                    <div class="nav-toggle collapsed-menu-toggle">
                        <div class="toggle-button-bar"></div>
                        <div class="toggle-button-bar"></div>
                        <div class="toggle-button-bar"></div>
                    </div>
                </div>
                <nav class="ddNavbar">
                    {% main_menu template="website/nav/main_menu_dropdown.html" %}
                </nav>
{#                <form class="header-search">#}
{#                    <input type="search" name="q" placeholder="Search HSPC">#}
{#                    <button type="submit">Go</button>#}
{#                </form>#}
            </header>
        </div>
    </div>
</div>


<main>
    <div class="container">
        {% block main %}
        {% endblock %}
    </div>
</main>


<!-- FOOTER -->

<footer>
    <div class="container">
        <div class="row">
            {#            <div class="col-sm-4">#}
            <div class="col-sm-4 col-sm-offset-2">
                <div class="essential-info ei-general">
                    <h4>&copy; 2019 Health Services Platform Consortium</h4>
                    <ul>
                        <li>
                            <a href="/privacy/">Privacy Statement</a>
                        </li>
                        <li>
                            <a href="/terms/">Terms & Conditions</a>
                        </li>
                        <li>
                            <a href="/membership/join/">Join Us</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                {% flat_menu 'sitemap' %}
            </div>
        </div>
    </div><!-- /.container -->
</footer>

{#<script src="{% static "scripts/pace.min.js" %}"></script>#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="{% static "scripts/nav.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/wagtailadmin/base.html
{% extends "wagtailadmin/base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}
    <style>
    /* Admin-related styles can be injected here */
    </style>
{% endblock %}

{% block branding_logo %}
    <img src="{% static "imgs/logo-pills-v1.png" %}" alt="HSPC Logo" width="80" style="background-color: #FFF; padding: 10px;" />
{% endblock %}

templates/wagtailadmin/home.html
{% extends "wagtailadmin/home.html" %}

{% block branding_welcome %}Welcome to the HSPC Website Management{% endblock %}

templates/wagtailadmin/login.html
{% extends "wagtailadmin/login.html" %}

{% block branding_login %}Sign in to HSPC Website Management{% endblock %}

templates/website/accounts/profile.html
{% extends "base.html" %}
{% block page_title %}Account Overview{% endblock %}
{% block main %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% if request.user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Your Account</h4>
                </div>
                <div class="panel-body">
                    <p>Information displayed below is provided by HPSC's OpenID Connect system. If information needs to be updated, please have it updated centrally. Upon your next login to this site your profile information will by synced.</p>
                </div>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>ID:</td>
                            <td>{{ request.user.username }}</td>
                        </tr>
                        <tr>
                            <td>Email:</td>
                            <td>{{ request.user.email }}</td>
                        </tr>
                        <tr>
                            <td>Name:</td>
                            <td>{{ request.user.first_name }} {{ request.user.last_name }}</td>
                        </tr>

                        <tr>
                            <td>Staff:</td>
                            <td>{{ request.user.is_staff|yesno:"Yes,No" }}</td>
                        </tr>

                        <tr>
                            <td>Superuser:</td>
                            <td>{{ request.user.is_superuser|yesno:"Yes,No" }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="panel-footer clearfix">
                    <a href="/auth/logout" class="btn btn-default pull-right">Logout</a>
                </div>
            </div>
            {% else %}
                <div class="panel panel-warning">
                <div class="panel-body">
                    <p>You aren't logged in.</p>
                </div>
                <div class="panel-footer clearfix">
                    <a href="{{ login_url }}" class="btn btn-default pull-right">Login</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/website/announcements.html
{% extends "base.html" %}
{% load static %}
{% load helpers %}

{% block page_title %}Announcements{% endblock %}
{% block styles %}
    <link href="{% static "styles/announcements.css" %}" rel="stylesheet">
{% endblock %}

{% block main %}

    <div class="col-md-8 col-md-offset-2">

        <h2 class="text-center">Announcements</h2>
        <hr>
        {% for announcement in announcement_list %}
            <div class="event-panel-container" id="announcement-{{ announcement.pk }}">
                <div class="panel panel-default event-panel">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Posted {{ announcement.created }}</strong></h3>
                    </div>
                    <div class="panel-body">
                        <p>{{ announcement.announcement|safe }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>


{% endblock %}

templates/website/basic_info_page.html
{% extends "base.html" %}
{% load static %}

{% load wagtailcore_tags %}

{% block page_title %}{{ page.title }}{% endblock %}
{% block styles %}
    <link href="{% static "styles/rich-text.css" %}" rel="stylesheet">
    <link href="{% static "styles/info-page.css" %}" rel="stylesheet">
{% endblock %}

{% block body_class %}template-homepage{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <h1>{{ page.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="info-page-body">
                {{ page.body|richtext }}
            </div>
        </div>
    </div>
{% endblock %}

templates/website/blocks/homepage_panel_block.html
{% load wagtailcore_tags %}

{# The image background_image url is currently broken https://github.com/wagtail/wagtail/issues/2087 #}
<div class="hspc-panel-bg" style="background-image: url({{ value.background_image }})">
    <div class="hspc-panel hspc-panel-4" style="background-color: {{ value.overlay_css_background_color }}">
        <div class="hspc-panel-face">
            <div class="hspc-panel-icon">
                <span class="material-icons">{{ value.material_icon_name }}</span>
            </div>
            <h2 class="hspc-panel-title">{{ value.title }}</h2>
        </div>
        <div class="hspc-panel-text">
            {{ value.body }}
        </div>
        {% if value.link_text != None and value.link_url != None %}
            <div class="hspc-panel-button-wrapper">
                <a class="btn btn-default hspc-panel-button" href="{{ value.link_url }}">{{ value.link_text }} {% if value.link_is_external %}<i class="material-icons">open_in_new</i>{% else %}&raquo;{% endif %}</a>
            </div>
        {% else %}
            <!-- Ensure both link_text and link_url are defined in the CMS -->
        {% endif %}
    </div>
</div>

templates/website/events.html
{% extends "base.html" %}
{% load static %}
{% load helpers %}

{% block page_title %}Events{% endblock %}
{% block styles %}
    <link href="{% static "styles/events.css" %}" rel="stylesheet">
{% endblock %}

{% block main %}

    <div class="col-md-8 col-md-offset-2">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#upcoming" aria-controls="home" role="tab" data-toggle="tab">Upcoming</a>
            </li>
            <li role="presentation">
                <a href="#archive" aria-controls="profile" role="tab" data-toggle="tab">Archive</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="upcoming">
                <h2 class="text-center">Upcoming Events</h2>
                <hr>
                {% get_current_events as current_events %}
                {% for event in current_events %}
                    <div class="event-panel-container" id="event-{{ event.pk }}">
                        <div class="panel panel-default event-panel">
                            <div class="panel-heading">
                                <h3 class="panel-title"><strong>{{ event.title }}</strong></h3>
                            </div>
                            <div class="panel-body">
                                <p><span class="glyphicon glyphicon-calendar"></span> {{ event.display_date }}</p>
                                <p><span class="glyphicon glyphicon-map-marker"></span> {{ event.location }}</p>
                                <p>{{ event.event_details|safe }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div role="tabpanel" class="tab-pane" id="archive">
                <h2 class="text-center">Past Events</h2>
                <hr>
                {% get_past_events as past_events %}
                {% for event in past_events %}
                    <div class="event-panel-container" id="event-{{ event.pk }}">
                        <div class="panel panel-default event-panel">
                            <div class="panel-heading">
                                <h3 class="panel-title"><strong>{{ event.title }}</strong></h3>
                            </div>
                            <div class="panel-body">
                                <p><em>{{ event.display_date }} - {{ event.location }}</em></p>
                                <p>{{ event.event_details|safe }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>


{% endblock %}

templates/website/home_page.html
{% extends "base.html" %}
{% load static %}
{% load helpers %}
{% load wagtailcore_tags %}

{% block page_title %}{{ page.title }}{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "styles/home.css" %}">
    <link rel="stylesheet" href="{% static "styles/typed.css" %}">
    <link rel="stylesheet" href="{% static "styles/hspc-panel.css" %}">
{% endblock %}

{% block body_class %}template-homepage{% endblock %}

{% block main %}

    {# Begin header/banner image Panel #}
    <div class="row">
        <div class="col-xs-12">
            <div id="hero-banner" style="background-image: url({% static "imgs/pulse-trace-blue.png" %})">
                <h1 class="hero-caption">HSP<span id="typedArea"></span></h1>
            </div>
        </div>
    </div>
    {# End header/banner image Panel #}

    {##}
    {#  This is currently on hold until https://github.com/wagtail/wagtail/issues/2087 is resolved #}
    {#    <div class="row">#}
    {#        {% for block in page.body %}#}
    {#            <div class="col-md-4">#}
    {#                {{ block }}#}
    {#            </div>#}
    {#        {% endfor %}#}
    {#    </div>#}

    {# Begin split 3-item Panel #}

    <div class="row hspc-panel-row">

        <div class="col-md-4 hspc-panel-column">
            <div class="hspc-panel" style="background-image: url(/static/imgs/wooden-pawns-optimized.jpeg)">
                <div class="hspc-panel-inner" style="background-color: rgba(21, 136, 23, 0.5)">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">assignment_turned_in</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Join HSPC</h2>
                        <p class="hspc-panel-text">
                            Be a part of the provider-led consortium for true healthcare interoperability.
                        </p>
                    </div>
                    <a href="/membership/join/" class="hspc-panel-action-button">Join Now &raquo;</a>
                </div>
            </div>
        </div>


        <div class="col-md-4 hspc-panel-column">
            <div class="hspc-panel" style="background-image: url(/static/imgs/solor-snip.png)">
                <div class="hspc-panel-inner" style="background-color: rgba(113, 113, 113, 0.5)">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">group</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Solor</h2>
                        <p class="hspc-panel-text">
                            HSPC is proud to have the SOLOR Launch as part of our 16th General Meeting.
                        <br>
                            Visit solor.io now!
                        </p>
                    </div>
                    <a class="hspc-panel-action-button" href="http://solor.io/"
                       target="_blank" rel="noopener">Solor.io <i class="material-icons">open_in_new</i></a>
                </div>
            </div>
        </div>


        <div class="col-md-4 hspc-panel-column">
            <div class="hspc-panel" style="background-image: url(/static/imgs/doctor-optimized.jpeg); background-position: right;">
                <div class="hspc-panel-inner" style="background-color: rgba(78, 32, 74, 0.75)">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">cached</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>CIIC</h2>
                        <p class="hspc-panel-text">
                            <em>&quot;Interoperability depends on implementing the same data model across systems.&quot;</em>
                        </p>
                    </div>
                    <a class="hspc-panel-action-button" target="_blank" rel="noopener" href="https://healthservices.atlassian.net/wiki/spaces/CIIC/overview">Learn More <i class="material-icons">open_in_new</i></a>
                </div>
            </div>
        </div>

    </div>
    {# End split 3-item Panel #}

    {# Begin Events Panel #}
    <div class="row hspc-panel-row">
        <div class="col-md-8 hspc-panel-column">

            <div class="hspc-panel" id="panel-events">
                <div class="hspc-panel-inner">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">event</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Upcoming Events</h2>
                        {% get_some_current_events as upcoming_events %}
                        <ul id="eventListing">
                            {% for event in upcoming_events %}
                                <li>
                                    <a href="/events/#event-{{ event.id }}">
                                        <h4>{{ event.display_date }}</h4>
                                        <p>{{ event.title }}</p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <a class="hspc-panel-action-button" href="/events/">See All Events &raquo;</a>
                </div>
            </div>
        </div>


        <div class="col-md-4 hspc-panel-column">
            <div class="hspc-panel" id="panel-announcements">
                <div class="hspc-panel-inner">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">record_voice_over</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Announcements</h2>
                        {% get_latest_announcement as latest_announcement %}
                        {{ latest_announcement.announcement|safe }}
                    </div>
                    <a class="hspc-panel-action-button" href="{% url "website:announcement-list" %}">See All &raquo;</a>
                </div>
            </div>
        </div>

    </div>

    {# Begin Benefactors Panel #}
    <div class="row hspc-panel-row">


        <div class="col-md-6 hspc-panel-column">
            <div class="hspc-panel" id="panel-newsroom">
                <div class="hspc-panel-inner">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">library_books</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Newsroom</h2>
                        <ul id="newsroomListing">
                            {% get_latest_newsroom_entries as some_newsroom_entries %}
                            {% for entry in some_newsroom_entries %}
                                <li>
                                    <a href="{{ entry.url }}">
                                        <h4>{{ entry.source }} - {{ entry.date }}</h4>
                                        <p>{{ entry.article_title }}</p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <a class="hspc-panel-action-button" href="{% url "website:newsroom-list" %}">See More &raquo;</a>
                </div>
            </div>
        </div>

        <div class="col-md-6 hspc-panel-column">
            <div class="hspc-panel" id="panel-benefactors">
                <div class="hspc-panel-inner">
                    <div class="hspc-panel-icon">
                        <span class="material-icons">favorite</span>
                    </div>
                    <div class="hspc-panel-body">
                        <h2>Our Benefactors</h2>
                        {% get_some_current_events as upcoming_events %}
                        <ul id="benefactorListing">
                            <li>
                                <a target="_blank" rel="noopener nofollow" href="https://intermountainhealthcare.org/">
                                    <h3 class="benefactor-name">Intermountain Healthcare</h3>
                                </a>
                            </li>
                            <li>
                                <a target="_blank" rel="noopener nofollow" href="https://www.lsu.edu/">
                                    <h3 class="benefactor-name">Louisiana State University Health</h3>
                                </a>
                            </li>
                            <li>
                                <a target="_blank" rel="noopener nofollow" href="https://www.va.gov/">
                                    <h3 class="benefactor-name">US Department of Veterans Affairs</h3>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {# End Benefactors Panel #}
{% endblock %}

{% block scripts %}
    <script src="{% static "bower_components/typed.js/dist/typed.min.js" %}"></script>
    <script>
        $(function () {
            $("#typedArea").typed({
                strings: ["Collaboration", "Community", "Consortium"],
                typeSpeed: 2
            });
        });
    </script>
{% endblock %}

templates/website/newsroom.html
{% extends "base.html" %}
{% load static %}
{% load helpers %}

{% block page_title %}Newsroom{% endblock %}
{% block styles %}
    <link href="{% static "styles/newsroom.css" %}" rel="stylesheet">
{% endblock %}

{% block main %}

    <div class="col-md-8 col-md-offset-2">

        <h2 class="text-center">Newsroom</h2>
        <hr>
        {% for news_mention in newsmention_list %}
            <div class="event-panel-container" id="news-{{ news_mention.pk }}">
                <div class="panel panel-default event-panel">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>{{ news_mention.source }} - {{ news_mention.date }}</strong></h3>
                    </div>
                    <div class="panel-body">
                        <a href="{{ news_mention.url }}">{{ news_mention.article_title }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>


{% endblock %}